# Generated by Django 5.1.7 on 2025-03-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.IntegerField()),
                (
                    "unit",
                    models.CharField(
                        choices=[("Month", "Month"), ("Year", "Year")],
                        default="Month",
                        max_length=20,
                    ),
                ),
                ("discount", models.IntegerField(default=0)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "final_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
            ],
        ),
    ]
